### ISSUE TITLE
Transaction aren't closed properly in GetApplicationSettings action

### ISSUE THREAD

**Issue by jpulleman** [jaspervanderhoek/MicroflowScheduledEventManager#1]
Transaction aren't closed properly in action\GetApplicationSettings.java if the resultsize().size > 0 is true.

Would suggest something like this to fix it:		

		IContext context = Core.createSystemContext();
		try {
			context.startTransaction();	
			List<IMendixObject> result = Core.retrieveXPathQuery(context, "//" + ApplicationSettings.entityName);
			if( result.size() > 0 )
				return result.get(0);
					
			IMendixObject settings = Core.instantiate(context, ApplicationSettings.entityName);
			Core.commit(context, settings);
			
			return settings;
		}
		catch( Exception e ) {
			context.rollbackTransAction();
			throw e;
		}
		finally {
			context.endTransaction();
		}

**Comment by jaspervanderhoek** [comment]
Fixed in the latest release 1.1
