### ISSUE TITLE
Importing v1.2 in Mx7.23.3

### ISSUE THREAD

**Issue by RVeenvliet** [jaspervanderhoek/MicroflowScheduledEventManager#2]
We upgraded our app from Mx 7.22 to Mx 7.32.3. 
We noticed we we're getting an error on "import aQute.bnd.service.action.Action;" in ScheduleManager.java. 
We used version 1.1 and upgraded to 1.2, this doesn't seem to have effect. Also the 1.2 keeps showing in the moduler as "__Version 1.1"

Removing this import, doesn't seem to have any effect on the functionality and it doesn't seem to be used. Could you please check and verify this import should/can be removed?

**Comment by jaspervanderhoek** [comment]
Your assumption is correct, that import shouldn't be there. 

I've just created a new release (1.3) that doesn't include this line.
